import type { Metadata } from "next";
import "./frontend.css";
import Header from "@/components/frontend/header";
import Footer from "@/components/frontend/footer";
import db from "@/db";
import { site_settings } from "@/db/schema/site_settings";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let [companyInfo] = await db
        .select({
            email: site_settings.email,
            company_name: site_settings.company_name,
            logo: site_settings.logo,
            instagram: site_settings.instagram,
            facebook: site_settings.facebook,
            linkedin: site_settings.linkedin,
            youtube: site_settings.youtube,
            tiktok: site_settings.tiktok,
            address: site_settings.address,
            contact_number_1: site_settings.contact_number_1,
            contact_number_2: site_settings.contact_number_2,
        })
        .from(site_settings)
        .limit(1);
    companyInfo = companyInfo ?? {};

    return (
        <html lang="en">
            <body className={`antialiased bg-red`}>
                <Header logo={companyInfo.logo} />
                {children}
                <Footer
                    logo={companyInfo.logo}
                    instagram={companyInfo.instagram}
                    facebook={companyInfo.facebook}
                    linkedin={companyInfo.linkedin}
                    youtube={companyInfo.youtube}
                    tiktok={companyInfo.tiktok}
                    address={companyInfo.address}
                    contact_number_1={companyInfo.contact_number_1}
                    contact_number_2={companyInfo.contact_number_2}
                    email={companyInfo.email}
                />
            </body>
        </html>
    );
}
